language: node_js
node_js:
- 8.9.1
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
branches:
  only:
  - source
script:
  - git config --global user.name Travis-CI
  - git config --global user.email ci@travis-ci.org
  - sed -i'' "s~git@github.com:venbaa/t3.git~https://${GH_TOKEN}:x-oauth-basic@github.com/venbaa/t3.git~" _config.yml
  - hexo clean
  - pwd #to identify present working directory
  - mkdir public && mkdir public/admin
  - cp source/admin/config.yml public/admin/config.yml
  - hexo generate
  - hexo deploy

# after_success: 
  # - cd ./public
  # - git init
  # - git add .
  # - git commit -m "Update site"
  # - git push -f -q "https://${GH_TOKEN}:x-oauth-basic@github.com/venbaa/t3.git" master